### ISSUE TITLE
Resource summary screen attachment list has no visible indication you can click for more info

### ISSUE THREAD

**Issue by SammyIsConfused** [openequella/openEQUELLA#3334]
**Describe the bug**
In the new UI, in a resource summary screen, there is no indicator next to an attachment that you can click to see more details, download the attachment, etc. when you click on the attachment row. 

This used to exist in the old UI in the form of a small dropdown arrow. During the CSS updates for the new UI this seems to have gone missing which causes a potential accessibility problem and confusion for new users.

**To Reproduce**

1. Go to the new UI. Create an item with attachments.
2. Go to the resource summary page for this item.
3. Note that there is no visible indicator that the attachment row is clickable. 
4. Note that if you hover over the attachment row it still has no visible indicator. 

**Expected behavior**
There should be some way to tell that there are more details for each attachment. This can be achieved with CSS. 

Note: In a selection session, this arrow can probably stay blank, as the selection button takes up the room the arrow would.

**Screenshots**
This is a video of my proposed CSS solution. Note that it only applies outside of a selection session. 

https://user-images.githubusercontent.com/24543345/130564160-db00c914-4bc3-42b8-a5ac-21a7165285e5.mp4

**Platform:**

- OpenEquella Version: 2020.2+
- OS: Agnostic
- Browser: Agnostic

**Additional context**
Here is some CSS I wrote to make the arrows work as they do in the video. Without it, no arrows show up at all.  This could be simplified slightly if we were to update the legacy.scss file so we don't need to use `!important` to override existing rules.
```css
/* Display the arrow */
.attachments-browse.structured li.attachmentrow .droparrow {
    display: block !important;
    position: absolute;
    right: 15px;
    top: 5px;
    height: 14px;
    width: 14px;
    background-repeat: no-repeat;
    text-indent: -9999px;
    border: none;
    background-color: transparent;
    background-image: url(../../images/baseline_arrow_drop_down_black_18dp.png);
  }

/* Change to up arrow when clicked, adjust vertical position accordingly */
.attachments-browse.structured li.attachmentrow.active .droparrow {
    background-image: url(../../images/baseline_arrow_drop_up_black_18dp.png);
    background-position: 0;
    top: 8px;
  }
  
/* Hide within selection session */
.selection .attcontainer .droparrow {
    display: none !important;
  }
  ```
